[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/r/*"
  to = "/.netlify/functions/microsite-meta"
  status = 200

[[redirects]]
  from = "/pay/*"
  to = "/.netlify/functions/microsite-meta"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Netlify Forms Configuration
# Email notifications will be sent to the email configured in Netlify dashboard
# Go to Site Settings > Forms > Form notifications to configure Gmail notifications
